name: Merge dev to main and sync crowdin (weekly)

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  crowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: sync crowdin
        uses: crowdin/github-action@v2
        with:
          config: crowdin.yml
          download_translations: true
          push_translations: true
          commit_message: "chore(i18n): sync translations"
          localization_branch_name: i18n
          create_pull_request: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
  i18n-to-dev:
    needs: crowdin

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout dev
        uses: actions/checkout@v4
        with:
          path: dev
          ref: dev

      - name: checkout i18n
        uses: actions/checkout@v4
        with:
          path: i18n
          ref: i18n

      - name: setup workspace
        uses: ./dev/.github/actions/setup
        with:
          root: dev/

      - name: sync dev and main
        working-directory: dev
        run: git pull origin main --rebase

      - name: delete old lang files
        working-directory: dev
        run: rm lang/values/*.json

      - name: write new lang files
        working-directory: dev
        run: pnpm crowdin ../i18n/lang/values

      - name: deploy
        working-directory: dev
        run: |
          if [ ! -z "$(git status -s)" ]; then
            git add .
            git commit -m "chore(i18n): sync translations" || true 
            git pull --ff-only
            git push
          fi
  merge:
    needs: i18n-to-dev

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: merge dev to main
        run: |
          git pull origin dev --ff-only
          git push origin main
